#ifndef CRYPTO_ERRORS_H
#define CRYPTO_ERRORS_H

typedef enum {
    CRYPTO_OK = 0,

    CRYPTO_ERR_KEYGEN,
    CRYPTO_ERR_INVALID_KEY,

    CRYPTO_ERR_ENCRYPT,
    CRYPTO_ERR_DECRYPT,
    CRYPTO_ERR_AUTH,

    CRYPTO_ERR_INVALID_INPUT,
    CRYPTO_ERR_INVALID_PARAMETER,

    CRYPTO_ERR_IO

} CryptoError;

#endif